CREATE TABLE permisos (
		"id" INTEGER PRIMARY KEY AUTOINCREMENT,  
        "tipo_embarcacion" VARCHAR(7) NOT NULL,    
        "estado" VARCHAR(19) NOT NULL,             
        "municipio" VARCHAR(33),                   
        "localidad" VARCHAR(326),                  
        "rnpa" VARCHAR(55),  
        "titular" VARCHAR(109) NOT NULL,           
        "especie" VARCHAR(216),                    
        "area" VARCHAR(677),                       
        "inicio" DATE,                      
        "termino" DATE,
		"cod_inegi" VARCHAR(55)
);

CREATE TABLE activos (
		"id" INTEGER PRIMARY KEY AUTOINCREMENT, 
        "rnpa" VARCHAR(55), 
        "nombre" VARCHAR(105), 
        "tipo" VARCHAR(38) NOT NULL, 
        "municipio" VARCHAR(49) NOT NULL, 
        "localidad" VARCHAR(60) NOT NULL, 
        "estado" VARCHAR(19) NOT NULL, 
        "ano_construccion" VARCHAR(13) NOT NULL,
		"cod_inegi" VARCHAR(55)
);

CREATE TABLE unidades_economicas (
		"id" INTEGER PRIMARY KEY AUTOINCREMENT,
        "tipo" VARCHAR(20), 
        "rnpa" VARCHAR(55), 
        "nombre" VARCHAR(116), 
        "fecha_registro" DATE, 
        "tipo_persona" VARCHAR(6), 
        "representante_legal" VARCHAR(77), 
        "estado" VARCHAR(19), 
        "municipio" VARCHAR(49), 
        "localidad" VARCHAR(60), 
        "inicio"  DATE, 
		"cod_inegi" VARCHAR(55)
);

CREATE TABLE embarcaciones (
	a DECIMAL NOT NULL, 
	"RNPA_ACTIVO" DECIMAL NOT NULL, 
	"NOMBRE_EMBARCACION" VARCHAR(56), 
	"RNPA_UNIDAD_ECONOMICA" DECIMAL NOT NULL, 
	"NOMBRE_UNIDAD_ECONOMICA" VARCHAR(109) NOT NULL, 
	"ESTADO" VARCHAR(19) NOT NULL, 
	"MUNICIPIO" VARCHAR(49) NOT NULL, 
	"LOCALIDAD" VARCHAR(60) NOT NULL, 
	"TIPO_EMBARCACION" VARCHAR(17) NOT NULL, 
	"FECHA_REGISTRO" VARCHAR(13) NOT NULL, 
	"NOMBRE_EMBARCACION_a" VARCHAR(86), 
	"TIPO" VARCHAR(38), 
	"MUNICIPIO_a" VARCHAR(49), 
	"LOCALIDAD_a" VARCHAR(60), 
	"ESTADO_a" VARCHAR(19), 
	"ANO_CONSTRUCCION" VARCHAR(13), 
	"TIPO_ua" VARCHAR(20), 
	"NOMBRE_UNIDAD_ECONOMICA_ua" VARCHAR(111), 
	"FECHA_REGISTRO_ua" VARCHAR(8), 
	"TIPO_PERSONA" VARCHAR(6), 
	"REPRESENTANTE_LEGAL" VARCHAR(54), 
	"ESTADO_ua" VARCHAR(19), 
	"MUNICIPIO_ua" VARCHAR(49), 
	"LOCALIDAD_ua" VARCHAR(60), 
	"INICIO" VARCHAR(13)
);
CREATE TABLE pescando.inegi (
	"COD_ESTADO" DECIMAL NOT NULL, 
	"ESTADO" VARCHAR(20) NOT NULL, 
	"NOM_ABR" VARCHAR(6) NOT NULL, 
	"COD_MUNICIPIO" DECIMAL NOT NULL, 
	"MUNICIPIO" VARCHAR(76) NOT NULL, 
	"COD_LOCALIDAD" DECIMAL NOT NULL, 
	"LOCALIDAD" VARCHAR(82) NOT NULL, 
	"AMBITO" VARCHAR(1) NOT NULL, 
	"LATITUD" DECIMAL NOT NULL, 
	"LONGITUD" DECIMAL NOT NULL, 
	"ALTITUD" VARCHAR(4) NOT NULL, 
	"CVE_CARTA" VARCHAR(6) NOT NULL
);
CREATE TABLE pescando.marginacion (
	"ENT" DECIMAL NOT NULL, 
	"NOM_ENT" VARCHAR(31) NOT NULL, 
	"MUN" DECIMAL NOT NULL, 
	"NOM_MUN" VARCHAR(35) NOT NULL, 
	"LOC" DECIMAL NOT NULL, 
	"NOM_LOC" VARCHAR(64) NOT NULL, 
	"POB_TOT" DECIMAL NOT NULL, 
	"VPH" DECIMAL NOT NULL, 
	"ANAL10" DECIMAL NOT NULL, 
	"SPRIM10" DECIMAL NOT NULL, 
	"SEXC10" DECIMAL NOT NULL, 
	"SEE10" DECIMAL NOT NULL, 
	"SAGUAE10" DECIMAL NOT NULL, 
	"PROM_OCC10" DECIMAL NOT NULL, 
	"PISOTIE10" DECIMAL NOT NULL, 
	"SREFRI10" DECIMAL NOT NULL, 
	"IM_2010" DECIMAL NOT NULL, 
	"GM_2010" VARCHAR(8) NOT NULL, 
	"IMC0A100" DECIMAL NOT NULL, 
	"LUG_NAL" DECIMAL NOT NULL, 
	"LUG_EDO" DECIMAL NOT NULL
);
